import { FieldMetadataType, MetadataWritability } from 'twenty-shared/types';

import { type UniversalFlatFieldMetadata } from 'src/engine/workspace-manager/workspace-migration/universal-flat-entity/types/universal-flat-field-metadata.type';

type PartialSystemFlatFieldMetadata<
  T extends FieldMetadataType = FieldMetadataType,
> = Omit<
  UniversalFlatFieldMetadata<T>,
  | 'applicationUniversalIdentifier'
  | 'universalIdentifier'
  | 'objectMetadataUniversalIdentifier'
  | 'createdAt'
  | 'updatedAt'
>;

const PARTIAL_ID_FIELD = {
  type: FieldMetadataType.UUID,
  name: 'id',
  label: 'ID',
  icon: 'Icon123',
  description: 'ID',
  isNullable: false,
  isUnique: true,
  isActive: true,
  isSystem: true,
  isSystemSideEffect: true,
  isUIEditable: false,
  writability: MetadataWritability.OPEN,
  isLabelSyncedWithName: false,
  defaultValue: 'uuid',
  options: null,
  overrides: null,
  morphId: null,
  universalSettings: null,
  relationTargetObjectMetadataUniversalIdentifier: null,
  relationTargetFieldMetadataUniversalIdentifier: null,
  viewFilterUniversalIdentifiers: [],
  viewFieldUniversalIdentifiers: [],
  kanbanAggregateOperationViewUniversalIdentifiers: [],
  calendarViewUniversalIdentifiers: [],
  calendarEndViewUniversalIdentifiers: [],
  mainGroupByFieldMetadataViewUniversalIdentifiers: [],
  fieldPermissionUniversalIdentifiers: [],
  viewSortUniversalIdentifiers: [],
  searchFieldMetadataUniversalIdentifiers: [],
} as const satisfies PartialSystemFlatFieldMetadata<FieldMetadataType.UUID>;

const PARTIAL_CREATED_AT_FIELD = {
  type: FieldMetadataType.DATE_TIME,
  name: 'createdAt',
  label: 'Дата создания',
  icon: 'IconCalendar',
  description: 'Дата создания',
  isNullable: false,
  isUnique: false,
  isActive: true,
  isSystem: true,
  isSystemSideEffect: true,
  isUIEditable: false,
  writability: MetadataWritability.OPEN,
  isLabelSyncedWithName: false,
  defaultValue: 'now',
  options: null,
  overrides: null,
  morphId: null,
  universalSettings: null,
  relationTargetObjectMetadataUniversalIdentifier: null,
  relationTargetFieldMetadataUniversalIdentifier: null,
  viewFilterUniversalIdentifiers: [],
  viewFieldUniversalIdentifiers: [],
  kanbanAggregateOperationViewUniversalIdentifiers: [],
  calendarViewUniversalIdentifiers: [],
  calendarEndViewUniversalIdentifiers: [],
  mainGroupByFieldMetadataViewUniversalIdentifiers: [],
  fieldPermissionUniversalIdentifiers: [],
  viewSortUniversalIdentifiers: [],
  searchFieldMetadataUniversalIdentifiers: [],
} as const satisfies PartialSystemFlatFieldMetadata<FieldMetadataType.DATE_TIME>;

const PARTIAL_UPDATED_AT_FIELD = {
  type: FieldMetadataType.DATE_TIME,
  name: 'updatedAt',
  label: 'Дата обновления',
  icon: 'IconCalendarClock',
  description: 'Дата последнего изменения записи',
  isNullable: false,
  isUnique: false,
  isActive: true,
  isSystem: true,
  isSystemSideEffect: true,
  isUIEditable: false,
  writability: MetadataWritability.OPEN,
  isLabelSyncedWithName: false,
  defaultValue: 'now',
  options: null,
  overrides: null,
  morphId: null,
  universalSettings: null,
  relationTargetObjectMetadataUniversalIdentifier: null,
  relationTargetFieldMetadataUniversalIdentifier: null,
  viewFilterUniversalIdentifiers: [],
  viewFieldUniversalIdentifiers: [],
  kanbanAggregateOperationViewUniversalIdentifiers: [],
  calendarViewUniversalIdentifiers: [],
  calendarEndViewUniversalIdentifiers: [],
  mainGroupByFieldMetadataViewUniversalIdentifiers: [],
  fieldPermissionUniversalIdentifiers: [],
  viewSortUniversalIdentifiers: [],
  searchFieldMetadataUniversalIdentifiers: [],
} as const satisfies PartialSystemFlatFieldMetadata<FieldMetadataType.DATE_TIME>;

const PARTIAL_DELETED_AT_FIELD = {
  type: FieldMetadataType.DATE_TIME,
  name: 'deletedAt',
  label: 'Дата удаления',
  icon: 'IconCalendarClock',
  description: 'Дата удаления',
  isNullable: true,
  isUnique: false,
  isActive: true,
  isSystem: true,
  isSystemSideEffect: true,
  isUIEditable: false,
  writability: MetadataWritability.OPEN,
  isLabelSyncedWithName: false,
  defaultValue: null,
  options: null,
  overrides: null,
  morphId: null,
  universalSettings: null,
  relationTargetObjectMetadataUniversalIdentifier: null,
  relationTargetFieldMetadataUniversalIdentifier: null,
  viewFilterUniversalIdentifiers: [],
  viewFieldUniversalIdentifiers: [],
  kanbanAggregateOperationViewUniversalIdentifiers: [],
  calendarViewUniversalIdentifiers: [],
  calendarEndViewUniversalIdentifiers: [],
  mainGroupByFieldMetadataViewUniversalIdentifiers: [],
  fieldPermissionUniversalIdentifiers: [],
  viewSortUniversalIdentifiers: [],
  searchFieldMetadataUniversalIdentifiers: [],
} as const satisfies PartialSystemFlatFieldMetadata<FieldMetadataType.DATE_TIME>;

const PARTIAL_CREATED_BY_FIELD = {
  type: FieldMetadataType.ACTOR,
  name: 'createdBy',
  label: 'Кем создано',
  icon: 'IconCreativeCommonsSa',
  description: 'Автор записи',
  isNullable: false,
  isUnique: false,
  isActive: true,
  isSystem: true,
  isSystemSideEffect: true,
  isUIEditable: false,
  writability: MetadataWritability.OPEN,
  isLabelSyncedWithName: false,
  defaultValue: { name: "''", source: "'MANUAL'" },
  options: null,
  overrides: null,
  morphId: null,
  universalSettings: null,
  relationTargetObjectMetadataUniversalIdentifier: null,
  relationTargetFieldMetadataUniversalIdentifier: null,
  viewFilterUniversalIdentifiers: [],
  viewFieldUniversalIdentifiers: [],
  kanbanAggregateOperationViewUniversalIdentifiers: [],
  calendarViewUniversalIdentifiers: [],
  calendarEndViewUniversalIdentifiers: [],
  mainGroupByFieldMetadataViewUniversalIdentifiers: [],
  fieldPermissionUniversalIdentifiers: [],
  viewSortUniversalIdentifiers: [],
  searchFieldMetadataUniversalIdentifiers: [],
} as const satisfies PartialSystemFlatFieldMetadata<FieldMetadataType.ACTOR>;

const PARTIAL_UPDATED_BY_FIELD = {
  type: FieldMetadataType.ACTOR,
  name: 'updatedBy',
  label: 'Кем обновлено',
  icon: 'IconUserCircle',
  description: 'Участник, последним изменивший запись',
  isNullable: false,
  isUnique: false,
  isActive: true,
  isSystem: true,
  isSystemSideEffect: true,
  isUIEditable: false,
  writability: MetadataWritability.OPEN,
  isLabelSyncedWithName: false,
  defaultValue: { name: "''", source: "'MANUAL'" },
  options: null,
  overrides: null,
  morphId: null,
  universalSettings: null,
  relationTargetObjectMetadataUniversalIdentifier: null,
  relationTargetFieldMetadataUniversalIdentifier: null,
  viewFilterUniversalIdentifiers: [],
  viewFieldUniversalIdentifiers: [],
  kanbanAggregateOperationViewUniversalIdentifiers: [],
  calendarViewUniversalIdentifiers: [],
  calendarEndViewUniversalIdentifiers: [],
  mainGroupByFieldMetadataViewUniversalIdentifiers: [],
  fieldPermissionUniversalIdentifiers: [],
  viewSortUniversalIdentifiers: [],
  searchFieldMetadataUniversalIdentifiers: [],
} as const satisfies PartialSystemFlatFieldMetadata<FieldMetadataType.ACTOR>;

const PARTIAL_POSITION_FIELD = {
  type: FieldMetadataType.POSITION,
  name: 'position',
  label: 'Позиция',
  icon: 'IconHierarchy2',
  description: 'Позиция',
  isNullable: false,
  isUnique: false,
  isActive: true,
  isSystem: true,
  isSystemSideEffect: true,
  isUIEditable: false,
  writability: MetadataWritability.OPEN,
  isLabelSyncedWithName: false,
  defaultValue: 0,
  options: null,
  overrides: null,
  morphId: null,
  universalSettings: null,
  relationTargetObjectMetadataUniversalIdentifier: null,
  relationTargetFieldMetadataUniversalIdentifier: null,
  viewFilterUniversalIdentifiers: [],
  viewFieldUniversalIdentifiers: [],
  kanbanAggregateOperationViewUniversalIdentifiers: [],
  calendarViewUniversalIdentifiers: [],
  calendarEndViewUniversalIdentifiers: [],
  mainGroupByFieldMetadataViewUniversalIdentifiers: [],
  fieldPermissionUniversalIdentifiers: [],
  viewSortUniversalIdentifiers: [],
  searchFieldMetadataUniversalIdentifiers: [],
} as const satisfies PartialSystemFlatFieldMetadata<FieldMetadataType.POSITION>;

const PARTIAL_SEARCH_VECTOR_FIELD = {
  type: FieldMetadataType.TS_VECTOR,
  name: 'searchVector',
  label: 'Поисковый вектор',
  icon: 'IconSearch',
  description: 'Поисковый вектор',
  isNullable: true,
  isUnique: false,
  isActive: true,
  isSystem: true,
  isSystemSideEffect: true,
  isUIEditable: false,
  writability: MetadataWritability.SYSTEM,
  isLabelSyncedWithName: false,
  defaultValue: null,
  options: null,
  overrides: null,
  morphId: null,
  // universalSettings for searchVector is computed at runtime
  // based on the name field (getTsVectorColumnExpressionFromFields)
  universalSettings: null,
  relationTargetObjectMetadataUniversalIdentifier: null,
  relationTargetFieldMetadataUniversalIdentifier: null,
  viewFilterUniversalIdentifiers: [],
  viewFieldUniversalIdentifiers: [],
  kanbanAggregateOperationViewUniversalIdentifiers: [],
  calendarViewUniversalIdentifiers: [],
  calendarEndViewUniversalIdentifiers: [],
  mainGroupByFieldMetadataViewUniversalIdentifiers: [],
  fieldPermissionUniversalIdentifiers: [],
  viewSortUniversalIdentifiers: [],
  searchFieldMetadataUniversalIdentifiers: [],
} as const satisfies PartialSystemFlatFieldMetadata<FieldMetadataType.TS_VECTOR>;

export const PARTIAL_SYSTEM_FLAT_FIELD_METADATAS = {
  id: PARTIAL_ID_FIELD,
  createdAt: PARTIAL_CREATED_AT_FIELD,
  updatedAt: PARTIAL_UPDATED_AT_FIELD,
  deletedAt: PARTIAL_DELETED_AT_FIELD,
  createdBy: PARTIAL_CREATED_BY_FIELD,
  updatedBy: PARTIAL_UPDATED_BY_FIELD,
  position: PARTIAL_POSITION_FIELD,
  searchVector: PARTIAL_SEARCH_VECTOR_FIELD,
} as const satisfies Record<string, PartialSystemFlatFieldMetadata>;
